# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import asp_pb2 as asp__pb2


class OneshotSolverStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.solve = channel.unary_unary(
        '/OneshotSolver/solve',
        request_serializer=asp__pb2.SolverJob.SerializeToString,
        response_deserializer=asp__pb2.SolveResultAnswersets.FromString,
        )


class OneshotSolverServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def solve(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OneshotSolverServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'solve': grpc.unary_unary_rpc_method_handler(
          servicer.solve,
          request_deserializer=asp__pb2.SolverJob.FromString,
          response_serializer=asp__pb2.SolveResultAnswersets.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'OneshotSolver', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
