# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: asp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='asp.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tasp.proto\"L\n\nParameters\x12\x19\n\x11number_of_answers\x18\x01 \x01(\x05\x12#\n\x1breturn_only_optimal_answers\x18\x02 \x01(\x08\"=\n\tSolverJob\x12\x0f\n\x07program\x18\x01 \x01(\t\x12\x1f\n\nparameters\x18\x02 \x01(\x0b\x32\x0b.Parameters\"*\n\x0b\x43ostElement\x12\r\n\x05level\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ost\x18\x02 \x01(\x05\"Q\n\tAnswerset\x12\r\n\x05\x61toms\x18\x01 \x03(\t\x12\x1b\n\x05\x63osts\x18\x02 \x03(\x0b\x32\x0c.CostElement\x12\x18\n\x10is_known_optimal\x18\x03 \x01(\x08\"D\n\x11ResultDescription\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x10\n\x08messages\x18\x03 \x03(\t\"]\n\x15SolveResultAnswersets\x12\'\n\x0b\x64\x65scription\x18\x01 \x01(\x0b\x32\x12.ResultDescription\x12\x1b\n\x07\x61nswers\x18\x02 \x03(\x0b\x32\n.Answerset2<\n\rOneshotSolver\x12+\n\x05solve\x12\n.SolverJob\x1a\x16.SolveResultAnswersetsb\x06proto3')
)




_PARAMETERS = _descriptor.Descriptor(
  name='Parameters',
  full_name='Parameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number_of_answers', full_name='Parameters.number_of_answers', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='return_only_optimal_answers', full_name='Parameters.return_only_optimal_answers', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=89,
)


_SOLVERJOB = _descriptor.Descriptor(
  name='SolverJob',
  full_name='SolverJob',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='program', full_name='SolverJob.program', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='SolverJob.parameters', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=152,
)


_COSTELEMENT = _descriptor.Descriptor(
  name='CostElement',
  full_name='CostElement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='level', full_name='CostElement.level', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cost', full_name='CostElement.cost', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=196,
)


_ANSWERSET = _descriptor.Descriptor(
  name='Answerset',
  full_name='Answerset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='atoms', full_name='Answerset.atoms', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='costs', full_name='Answerset.costs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_known_optimal', full_name='Answerset.is_known_optimal', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=279,
)


_RESULTDESCRIPTION = _descriptor.Descriptor(
  name='ResultDescription',
  full_name='ResultDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='ResultDescription.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='ResultDescription.code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='messages', full_name='ResultDescription.messages', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=349,
)


_SOLVERESULTANSWERSETS = _descriptor.Descriptor(
  name='SolveResultAnswersets',
  full_name='SolveResultAnswersets',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='SolveResultAnswersets.description', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='answers', full_name='SolveResultAnswersets.answers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=444,
)

_SOLVERJOB.fields_by_name['parameters'].message_type = _PARAMETERS
_ANSWERSET.fields_by_name['costs'].message_type = _COSTELEMENT
_SOLVERESULTANSWERSETS.fields_by_name['description'].message_type = _RESULTDESCRIPTION
_SOLVERESULTANSWERSETS.fields_by_name['answers'].message_type = _ANSWERSET
DESCRIPTOR.message_types_by_name['Parameters'] = _PARAMETERS
DESCRIPTOR.message_types_by_name['SolverJob'] = _SOLVERJOB
DESCRIPTOR.message_types_by_name['CostElement'] = _COSTELEMENT
DESCRIPTOR.message_types_by_name['Answerset'] = _ANSWERSET
DESCRIPTOR.message_types_by_name['ResultDescription'] = _RESULTDESCRIPTION
DESCRIPTOR.message_types_by_name['SolveResultAnswersets'] = _SOLVERESULTANSWERSETS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Parameters = _reflection.GeneratedProtocolMessageType('Parameters', (_message.Message,), dict(
  DESCRIPTOR = _PARAMETERS,
  __module__ = 'asp_pb2'
  # @@protoc_insertion_point(class_scope:Parameters)
  ))
_sym_db.RegisterMessage(Parameters)

SolverJob = _reflection.GeneratedProtocolMessageType('SolverJob', (_message.Message,), dict(
  DESCRIPTOR = _SOLVERJOB,
  __module__ = 'asp_pb2'
  # @@protoc_insertion_point(class_scope:SolverJob)
  ))
_sym_db.RegisterMessage(SolverJob)

CostElement = _reflection.GeneratedProtocolMessageType('CostElement', (_message.Message,), dict(
  DESCRIPTOR = _COSTELEMENT,
  __module__ = 'asp_pb2'
  # @@protoc_insertion_point(class_scope:CostElement)
  ))
_sym_db.RegisterMessage(CostElement)

Answerset = _reflection.GeneratedProtocolMessageType('Answerset', (_message.Message,), dict(
  DESCRIPTOR = _ANSWERSET,
  __module__ = 'asp_pb2'
  # @@protoc_insertion_point(class_scope:Answerset)
  ))
_sym_db.RegisterMessage(Answerset)

ResultDescription = _reflection.GeneratedProtocolMessageType('ResultDescription', (_message.Message,), dict(
  DESCRIPTOR = _RESULTDESCRIPTION,
  __module__ = 'asp_pb2'
  # @@protoc_insertion_point(class_scope:ResultDescription)
  ))
_sym_db.RegisterMessage(ResultDescription)

SolveResultAnswersets = _reflection.GeneratedProtocolMessageType('SolveResultAnswersets', (_message.Message,), dict(
  DESCRIPTOR = _SOLVERESULTANSWERSETS,
  __module__ = 'asp_pb2'
  # @@protoc_insertion_point(class_scope:SolveResultAnswersets)
  ))
_sym_db.RegisterMessage(SolveResultAnswersets)



_ONESHOTSOLVER = _descriptor.ServiceDescriptor(
  name='OneshotSolver',
  full_name='OneshotSolver',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=446,
  serialized_end=506,
  methods=[
  _descriptor.MethodDescriptor(
    name='solve',
    full_name='OneshotSolver.solve',
    index=0,
    containing_service=None,
    input_type=_SOLVERJOB,
    output_type=_SOLVERESULTANSWERSETS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ONESHOTSOLVER)

DESCRIPTOR.services_by_name['OneshotSolver'] = _ONESHOTSOLVER

# @@protoc_insertion_point(module_scope)
