# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import sudoku_gui_pb2 as sudoku__gui__pb2


class SudokuDesignEvaluationRequestDataBrokerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.requestSudokuEvaluation = channel.unary_unary(
        '/SudokuDesignEvaluationRequestDataBroker/requestSudokuEvaluation',
        request_serializer=sudoku__gui__pb2.SudokuDesignEvaluationRequest.SerializeToString,
        response_deserializer=sudoku__gui__pb2.SudokuDesignEvaluationJob.FromString,
        )


class SudokuDesignEvaluationRequestDataBrokerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def requestSudokuEvaluation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SudokuDesignEvaluationRequestDataBrokerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'requestSudokuEvaluation': grpc.unary_unary_rpc_method_handler(
          servicer.requestSudokuEvaluation,
          request_deserializer=sudoku__gui__pb2.SudokuDesignEvaluationRequest.FromString,
          response_serializer=sudoku__gui__pb2.SudokuDesignEvaluationJob.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SudokuDesignEvaluationRequestDataBroker', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class SudokuDesignEvaluationResultProcessorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.processEvaluationResult = channel.unary_unary(
        '/SudokuDesignEvaluationResultProcessor/processEvaluationResult',
        request_serializer=sudoku__gui__pb2.SudokuDesignEvaluationResult.SerializeToString,
        response_deserializer=sudoku__gui__pb2.Empty.FromString,
        )


class SudokuDesignEvaluationResultProcessorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def processEvaluationResult(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SudokuDesignEvaluationResultProcessorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'processEvaluationResult': grpc.unary_unary_rpc_method_handler(
          servicer.processEvaluationResult,
          request_deserializer=sudoku__gui__pb2.SudokuDesignEvaluationResult.FromString,
          response_serializer=sudoku__gui__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SudokuDesignEvaluationResultProcessor', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
