# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import sudoku_design_evaluator_pb2 as sudoku__design__evaluator__pb2


class SudokuDesignEvaluationProblemEncoderStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.evaluateSudokuDesign = channel.unary_unary(
        '/SudokuDesignEvaluationProblemEncoder/evaluateSudokuDesign',
        request_serializer=sudoku__design__evaluator__pb2.SudokuDesignEvaluationJob.SerializeToString,
        response_deserializer=sudoku__design__evaluator__pb2.SolverJob.FromString,
        )


class SudokuDesignEvaluationProblemEncoderServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def evaluateSudokuDesign(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SudokuDesignEvaluationProblemEncoderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'evaluateSudokuDesign': grpc.unary_unary_rpc_method_handler(
          servicer.evaluateSudokuDesign,
          request_deserializer=sudoku__design__evaluator__pb2.SudokuDesignEvaluationJob.FromString,
          response_serializer=sudoku__design__evaluator__pb2.SolverJob.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SudokuDesignEvaluationProblemEncoder', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class SudokuDesignEvaluationResultDecoderStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.processEvaluationResult = channel.unary_unary(
        '/SudokuDesignEvaluationResultDecoder/processEvaluationResult',
        request_serializer=sudoku__design__evaluator__pb2.SolveResultAnswersets.SerializeToString,
        response_deserializer=sudoku__design__evaluator__pb2.SudokuDesignEvaluationResult.FromString,
        )


class SudokuDesignEvaluationResultDecoderServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def processEvaluationResult(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SudokuDesignEvaluationResultDecoderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'processEvaluationResult': grpc.unary_unary_rpc_method_handler(
          servicer.processEvaluationResult,
          request_deserializer=sudoku__design__evaluator__pb2.SolveResultAnswersets.FromString,
          response_serializer=sudoku__design__evaluator__pb2.SudokuDesignEvaluationResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SudokuDesignEvaluationResultDecoder', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
